name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'
      - name: Build Project
        run: npm install && npm run build
      - name: Setup Lighthouse
        run: npm install -g @lhci/cli@latest
      - name: Lighthouse Report
        run: lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=./dist

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'
      - name: Install Stylelint
        run: npm install
      - name: Stylelint Report
        run: npm run stylelint

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: ESLint Report
        run: npm run lint

  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then 
            echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it and update your .gitignore."; 
            exit 1; 
          fi